name: containerizing the app
on:
    push:
        branches:
            - master
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: setup jdk-21
              uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'temurin'
            - name: Build Java
              run: mvn clean install
            - name: setup docker build
              uses: docker/setup-buildx-action@v3
            - name: Login in to Docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/java-ci-demo:latest
