apiVersion: v1
kind: Service
metadata:
 name: java-app-service
spec:
 type: NodePort
 ports:
 - protocol: TCP
   port: 80
   targetPort: 8080
   nodePort: 30080
 selector:
   app: java-app