name: my first ci pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkoutcode
        uses: actions/checkout@v3
      - name: print hello
        run: echo "print hello from github actions"
